services:
  bouncer:
    build:
      context: .
    command: go-bouncer --addr 0.0.0.0:8000
    ports:
      - 8000:8000
    environment:
      BOUNCER_DB_DSN: "bounceruser:bouncerpass@tcp(mysql:3306)/bouncerdb"
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: bouncerdb
      MYSQL_USER: bounceruser
      MYSQL_PASSWORD: bouncerpass
    volumes:
      - ./docker/initdb.d/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD", "mysql", "-u", "root", "-prootpass", "--execute", "SHOW DATABASES;"]
      interval: 3s
      retries: 5
      timeout: 5s
  nginx:
    image: nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 18000:80
    depends_on:
      - bouncer
