pipeline {
  agent any
  libraries {
    lib('fxtest@1.10')
  }
  triggers {
    pollSCM('H/5 * * * *')
  }
  options {
    ansiColor('xterm')
    timestamps()
    timeout(time: 5, unit: 'MINUTES')
  }
  stages {
    stage('Lint') {
      agent {
        dockerfile {
          dir 'tests/e2e'
        }
      }
      steps {
        sh "flake8 tests/e2e/"
      }
    }
    stage('Test') {
      agent {
        dockerfile {
          dir 'tests/e2e'
        }
      }
      environment {
        PYTEST_PROCESSES = "${PYTEST_PROCESSES ?: "auto"}"
        PULSE = credentials('PULSE')
      }
      steps {
        sh "pytest " +
          "-n=${PYTEST_PROCESSES} " +
          "--color=yes " +
          "--junit-xml=tests/e2e/results/junit.xml " +
          "--html=tests/e2e/results/index.html " +
          "--self-contained-html " +
          "--log-raw=tests/e2e/results/raw.txt " +
          "--log-tbpl=tests/e2e/results/tbpl.txt " +
          "tests/e2e/"
      }
      post {
        always {
          stash includes: 'tests/e2e/results/*', name: 'results'
          archiveArtifacts 'tests/e2e/results/*'
          junit 'tests/e2e/results/*.xml'
          submitToActiveData('tests/e2e/results/raw.txt')
          submitToTreeherder('go-bouncer', 'T', 'Tests', 'tests/e2e/results/*', 'tests/e2e/results/tbpl.txt')
        }
      }
    }
  }
  post {
    always {
      unstash 'results'
      publishHTML(target: [
        allowMissing: false,
        alwaysLinkToLastBuild: true,
        keepAll: true,
        reportDir: 'tests/e2e/results',
        reportFiles: 'index.html',
        reportName: 'HTML Report'])
    }
    changed {
      ircNotification()
    }
    failure {
      emailext(
        attachLog: true,
        body: '$BUILD_URL\n\n$FAILED_TESTS',
        replyTo: '$DEFAULT_REPLYTO',
        subject: '$DEFAULT_SUBJECT',
        to: '$DEFAULT_RECIPIENTS')
    }
  }
}
