pipeline {
  agent any
  libraries {
    lib('fxtest@1.9')
  }
  options {
    ansiColor('xterm')
    timestamps()
    timeout(time: 5, unit: 'MINUTES')
  }
  environment {
    PYTEST_ADDOPTS = "-n=10 --color=yes"
    PULSE = credentials('PULSE')
  }
  stages {
    stage('Lint') {
      steps {
        sh "tox -c tests/e2e/tox.ini -e flake8"
      }
    }
    stage('Test') {
      steps {
        sh "tox -c tests/e2e/tox.ini -e py27"
      }
      post {
        always {
          archiveArtifacts 'tests/e2e/results/*'
          junit 'tests/e2e/results/*.xml'
          submitToActiveData('tests/e2e/results/py27_raw.txt')
          submitToTreeherder('go-bouncer', 'T', 'Tests', 'tests/e2e/results/*', 'tests/e2e/results/py27_tbpl.txt')
        }
      }
    }
  }
  post {
    failure {
      emailext(
        attachLog: true,
        body: '$BUILD_URL\n\n$FAILED_TESTS',
        replyTo: '$DEFAULT_REPLYTO',
        subject: '$DEFAULT_SUBJECT',
        to: '$DEFAULT_RECIPIENTS')
    }
    changed {
      ircNotification()
    }
  }
}
